name: "Pull Requests"

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - ".gitginore"
      - "README.md"
      - "CONTRIBUTING.md"
      - "LICENSE"

jobs:
  build-linux:
    name: "Linux"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Install Go"
        uses: "actions/setup-go@v2"
        with:
          go-version: "1.15.x"
      - name: "Checkout"
        uses: "actions/checkout@v2"
      - name: "Init"
        run: "make init"
      - name: "Fetch dependencies"
        run: "make dependencies"
      - name: "Lint"
        run: "make lint"
      - name: "Build"
        run: "make build"
      - name: "Test"
        run: "make test"
