name: Pull Requests

on:
  pull_request:
    paths-ignore:
      - docs/**
      - .gitginore
      - README.md
      - CONTRIBUTING.md
      - LICENSE

jobs:
  build-linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Checkout
        uses: actions/checkout@v2
      - name: Initialize
        run: make init
      - name: Fetch dependencies
        run: make dependencies
      - name: Lint source
        run: make lint
      - name: Build source
        run: make build
      - name: Unit test
        run: make test
      - name: Functional test
        run: ./bin/assert ./tests/test.yaml ./tests/chart-example
